import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>PillPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main
      // style={{
      //   display: "flex",
      //   flexDirection: "column",
      //   alignItems: "center",
      // }}
      >
        {/* <div style={{ width: "80vw", height: "30em", background: "red" }}></div> */}
      </main>
    </>
  );
}
